-- servants
INSERT INTO `card` (`type`, `order`, `name`, `star`, `class`, `url`, `created_by`, `updated_by`) VALUES
  (1,   1, '玛修・基列莱特', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/001.jpg', -1, -1),
  (1,   2, '阿尔托莉雅・潘德拉贡', 5, null, '/bundles/kazefgostatscarddrawing/images/servants/002.jpg', -1, -1),
  (1,   3, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/003.jpg', -1, -1),
  (1,   4, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/004.jpg', -1, -1),
  (1,   5, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/005.jpg', -1, -1),
  (1,   6, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/006.jpg', -1, -1),
  (1,   7, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/007.jpg', -1, -1),
  (1,   8, '', 5, null, '/bundles/kazefgostatscarddrawing/images/servants/008.jpg', -1, -1),
  (1,   9, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/009.jpg', -1, -1),
  (1,  10, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/010.jpg', -1, -1),

  (1,  11, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/011.jpg', -1, -1),
  (1,  12, '', 5, null, '/bundles/kazefgostatscarddrawing/images/servants/012.jpg', -1, -1),
  (1,  13, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/013.jpg', -1, -1),
  (1,  14, '', 5, null, '/bundles/kazefgostatscarddrawing/images/servants/014.jpg', -1, -1),
  (1,  15, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/015.jpg', -1, -1),
  (1,  16, '', 1, null, '/bundles/kazefgostatscarddrawing/images/servants/016.jpg', -1, -1),
  (1,  17, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/017.jpg', -1, -1),
  (1,  18, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/018.jpg', -1, -1),
  (1,  19, '', 2, null, '/bundles/kazefgostatscarddrawing/images/servants/019.jpg', -1, -1),
  (1,  20, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/020.jpg', -1, -1),

  (1,  21, '', 2, null, '/bundles/kazefgostatscarddrawing/images/servants/021.jpg', -1, -1),
  (1,  22, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/022.jpg', -1, -1),
  (1,  23, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/023.jpg', -1, -1),
  (1,  24, '', 2, null, '/bundles/kazefgostatscarddrawing/images/servants/024.jpg', -1, -1),
  (1,  25, '', 2, null, '/bundles/kazefgostatscarddrawing/images/servants/025.jpg', -1, -1),
  (1,  26, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/026.jpg', -1, -1),
  (1,  27, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/027.jpg', -1, -1),
  (1,  28, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/028.jpg', -1, -1),
  (1,  29, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/029.jpg', -1, -1),
  (1,  30, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/030.jpg', -1, -1),

  (1,  31, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/031.jpg', -1, -1),
  (1,  32, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/032.jpg', -1, -1),
  (1,  33, '', 2, null, '/bundles/kazefgostatscarddrawing/images/servants/033.jpg', -1, -1),
  (1,  34, '', 2, null, '/bundles/kazefgostatscarddrawing/images/servants/034.jpg', -1, -1),
  (1,  35, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/035.jpg', -1, -1),
  (1,  36, '', 1, null, '/bundles/kazefgostatscarddrawing/images/servants/036.jpg', -1, -1),
  (1,  37, '', 5, null, '/bundles/kazefgostatscarddrawing/images/servants/037.jpg', -1, -1),
  (1,  38, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/038.jpg', -1, -1),
  (1,  39, '', 1, null, '/bundles/kazefgostatscarddrawing/images/servants/039.jpg', -1, -1),
  (1,  40, '', 2, null, '/bundles/kazefgostatscarddrawing/images/servants/040.jpg', -1, -1),

  (1,  41, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/041.jpg', -1, -1),
  (1,  42, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/042.jpg', -1, -1),
  (1,  43, '', 2, null, '/bundles/kazefgostatscarddrawing/images/servants/043.jpg', -1, -1),
  (1,  44, '', 2, null, '/bundles/kazefgostatscarddrawing/images/servants/044.jpg', -1, -1),
  (1,  45, '', 1, null, '/bundles/kazefgostatscarddrawing/images/servants/045.jpg', -1, -1),
  (1,  46, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/046.jpg', -1, -1),
  (1,  47, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/047.jpg', -1, -1),
  (1,  48, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/048.jpg', -1, -1),
  (1,  49, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/049.jpg', -1, -1),
  (1,  50, '', 1, null, '/bundles/kazefgostatscarddrawing/images/servants/050.jpg', -1, -1),

  (1,  51, '', 5, null, '/bundles/kazefgostatscarddrawing/images/servants/051.jpg', -1, -1),
  (1,  52, '', 5, null, '/bundles/kazefgostatscarddrawing/images/servants/052.jpg', -1, -1),
  (1,  53, '', 1, null, '/bundles/kazefgostatscarddrawing/images/servants/053.jpg', -1, -1),
  (1,  54, '', 2, null, '/bundles/kazefgostatscarddrawing/images/servants/054.jpg', -1, -1),
  (1,  55, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/055.jpg', -1, -1),
  (1,  56, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/056.jpg', -1, -1),
  (1,  57, '', 2, null, '/bundles/kazefgostatscarddrawing/images/servants/057.jpg', -1, -1),
  (1,  58, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/058.jpg', -1, -1),
  (1,  59, '', 5, null, '/bundles/kazefgostatscarddrawing/images/servants/059.jpg', -1, -1),
  (1,  60, '', 5, null, '/bundles/kazefgostatscarddrawing/images/servants/060.jpg', -1, -1),

  (1,  61, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/061.jpg', -1, -1),
  (1,  62, '', 5, null, '/bundles/kazefgostatscarddrawing/images/servants/062.jpg', -1, -1),
  (1,  63, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/063.jpg', -1, -1),
  (1,  64, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/064.jpg', -1, -1),
  (1,  65, '', 5, null, '/bundles/kazefgostatscarddrawing/images/servants/065.jpg', -1, -1),
  (1,  66, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/066.jpg', -1, -1),
  (1,  67, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/067.jpg', -1, -1),
  (1,  68, '', 5, null, '/bundles/kazefgostatscarddrawing/images/servants/068.jpg', -1, -1),
  (1,  69, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/069.jpg', -1, -1),
  (1,  70, '', 5, null, '/bundles/kazefgostatscarddrawing/images/servants/070.jpg', -1, -1),

  (1,  71, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/071.jpg', -1, -1),
  (1,  72, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/072.jpg', -1, -1),
  (1,  73, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/073.jpg', -1, -1),
  (1,  74, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/074.jpg', -1, -1),
  (1,  75, '', 5, null, '/bundles/kazefgostatscarddrawing/images/servants/075.jpg', -1, -1),
  (1,  76, '', 5, null, '/bundles/kazefgostatscarddrawing/images/servants/076.jpg', -1, -1),
  (1,  77, '', 5, null, '/bundles/kazefgostatscarddrawing/images/servants/077.jpg', -1, -1),
  (1,  78, '', 4, null, '/bundles/kazefgostatscarddrawing/images/servants/078.jpg', -1, -1),
  (1,  79, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/079.jpg', -1, -1),
  (1,  80, '', 3, null, '/bundles/kazefgostatscarddrawing/images/servants/080.jpg', -1, -1);


-- craft essences
INSERT INTO `card` (`type`, `order`, `name`, `star`, `class`, `url`, `created_by`, `updated_by`) VALUES
  (2,   1, '顽强', 1, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/001.jpg', -1, -1),
  (2,   2, '冥想', 1, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/002.jpg', -1, -1),
  (2,   3, '', 1, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/003.jpg', -1, -1),
  (2,   4, '', 1, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/004.jpg', -1, -1),
  (2,   5, '', 1, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/005.jpg', -1, -1),
  (2,   6, '', 2, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/006.jpg', -1, -1),
  (2,   7, '', 2, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/007.jpg', -1, -1),
  (2,   8, '', 2, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/008.jpg', -1, -1),
  (2,   9, '', 2, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/009.jpg', -1, -1),
  (2,  10, '', 2, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/010.jpg', -1, -1),

  (2,  11, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/011.jpg', -1, -1),
  (2,  12, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/012.jpg', -1, -1),
  (2,  13, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/013.jpg', -1, -1),
  (2,  14, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/014.jpg', -1, -1),
  (2,  15, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/015.jpg', -1, -1),
  (2,  16, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/016.jpg', -1, -1),
  (2,  17, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/017.jpg', -1, -1),
  (2,  18, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/018.jpg', -1, -1),
  (2,  19, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/019.jpg', -1, -1),
  (2,  20, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/020.jpg', -1, -1),

  (2,  21, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/021.jpg', -1, -1),
  (2,  22, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/022.jpg', -1, -1),
  (2,  23, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/023.jpg', -1, -1),
  (2,  24, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/024.jpg', -1, -1),
  (2,  25, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/025.jpg', -1, -1),
  (2,  26, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/026.jpg', -1, -1),
  (2,  27, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/027.jpg', -1, -1),
  (2,  28, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/028.jpg', -1, -1),
  (2,  29, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/029.jpg', -1, -1),
  (2,  30, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/030.jpg', -1, -1),

  (2,  31, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/031.jpg', -1, -1),
  (2,  32, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/032.jpg', -1, -1),
  (2,  33, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/033.jpg', -1, -1),
  (2,  34, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/034.jpg', -1, -1),
  (2,  35, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/035.jpg', -1, -1),
  (2,  36, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/036.jpg', -1, -1),
  (2,  37, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/037.jpg', -1, -1),
  (2,  38, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/038.jpg', -1, -1),
  (2,  39, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/039.jpg', -1, -1),
  (2,  40, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/040.jpg', -1, -1),

  (2,  41, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/041.jpg', -1, -1),
  (2,  42, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/042.jpg', -1, -1),
  (2,  43, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/043.jpg', -1, -1),
  (2,  44, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/044.jpg', -1, -1),
  (2,  45, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/045.jpg', -1, -1),
  (2,  46, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/046.jpg', -1, -1),
  (2,  47, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/047.jpg', -1, -1),
  (2,  48, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/048.jpg', -1, -1),
  (2,  49, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/049.jpg', -1, -1),
  (2,  50, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/050.jpg', -1, -1),

  (2,  51, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/051.jpg', -1, -1),
  (2,  52, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/052.jpg', -1, -1),
  (2,  53, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/053.jpg', -1, -1),
  (2,  54, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/054.jpg', -1, -1),
  (2,  55, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/055.jpg', -1, -1),
  (2,  56, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/056.jpg', -1, -1),
  (2,  57, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/057.jpg', -1, -1),
  (2,  58, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/058.jpg', -1, -1),
  (2,  59, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/059.jpg', -1, -1),
  (2,  60, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/060.jpg', -1, -1),

  (2,  61, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/061.jpg', -1, -1),
  (2,  62, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/062.jpg', -1, -1),
  (2,  63, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/063.jpg', -1, -1),
  (2,  64, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/064.jpg', -1, -1),
  (2,  65, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/065.jpg', -1, -1),
  (2,  66, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/066.jpg', -1, -1),
  (2,  67, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/067.jpg', -1, -1),
  (2,  68, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/068.jpg', -1, -1),
  (2,  69, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/069.jpg', -1, -1),
  (2,  70, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/070.jpg', -1, -1),

  (2,  71, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/071.jpg', -1, -1),
  (2,  72, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/072.jpg', -1, -1),
  (2,  73, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/073.jpg', -1, -1),
  (2,  74, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/074.jpg', -1, -1),
  (2,  75, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/075.jpg', -1, -1),
  (2,  76, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/076.jpg', -1, -1),
  (2,  77, '', 4, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/077.jpg', -1, -1),
  (2,  78, '', 3, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/078.jpg', -1, -1),
  (2,  79, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/079.jpg', -1, -1),
  (2,  80, '', 5, null, '/bundles/kazefgostatscarddrawing/images/craft_essences/080.jpg', -1, -1);
